In [38]:
import MetaTrader5 as mt5
import pandas as pd
%matplotlib nbagg

In [2]:
mt5.initialize()

True

In [3]:
audusd = pd.DataFrame(mt5.copy_rates_from_pos('AUDUSD', mt5.TIMEFRAME_H1, 1, 5)).drop(columns=['spread', 'real_volume'])
usdzar = pd.DataFrame(mt5.copy_rates_from_pos('USDZAR', mt5.TIMEFRAME_H1, 1, 5)).drop(columns=['spread', 'real_volume'])
gbpusd = pd.DataFrame(mt5.copy_rates_from_pos('GBPUSD', mt5.TIMEFRAME_H1, 1, 5)).drop(columns=['spread', 'real_volume'])
usdchf = pd.DataFrame(mt5.copy_rates_from_pos('USDCHF', mt5.TIMEFRAME_H1, 1, 5)).drop(columns=['spread', 'real_volume'])
dax = pd.DataFrame(mt5.copy_rates_from_pos('DE30', mt5.TIMEFRAME_H1, 1, 5)).drop(columns=['spread', 'real_volume'])
snp500 = pd.DataFrame(mt5.copy_rates_from_pos('US500', mt5.TIMEFRAME_H1, 1, 5)).drop(columns=['spread', 'real_volume'])

audusd['time'] = pd.to_datetime(audusd['time'], unit='s')
usdzar['time'] = pd.to_datetime(usdzar['time'], unit='s')
gbpusd['time'] = pd.to_datetime(gbpusd['time'], unit='s')
usdchf['time'] = pd.to_datetime(usdchf['time'], unit='s')
dax['time'] = pd.to_datetime(dax['time'], unit='s')
snp500['time'] = pd.to_datetime(snp500['time'], unit='s')

audusd.set_index(keys=['time'], inplace=True)
usdzar.set_index(keys=['time'], inplace=True)
gbpusd.set_index(keys=['time'], inplace=True)
usdchf.set_index(keys=['time'], inplace=True)
dax.set_index(keys=['time'], inplace=True)
snp500.set_index(keys=['time'], inplace=True)

In [5]:
audusd.head(3)

                        open     high      low    close  tick_volume
time
2020-07-17 18:00:00  0.69832  0.69935  0.69829  0.69933         2126
2020-07-17 19:00:00  0.69933  0.69994  0.69929  0.69959         1455
2020-07-17 20:00:00  0.69959  0.69985  0.69911  0.69963         1741

In [6]:
usdzar.head(3)

                         open      high       low     close  tick_volume
time
2020-07-17 18:00:00  16.65980  16.68030  16.63490  16.65983         2050
2020-07-17 19:00:00  16.65983  16.66897  16.64968  16.66230         1498
2020-07-17 20:00:00  16.66210  16.68093  16.66016  16.68093         3772

# y/x x/z
### AUDUSD USDZAR

# Inversing the values in a DataFrame (1/val)

In [4]:
 audzar = audusd[['open', 'high', 'low', 'close']] * usdzar[['open', 'high', 'low', 'close']]
 audzar['vol'] = (audusd['tick_volume'] + usdzar['tick_volume']) / 2

 audzar

                          open       high        low      close     vol
time
2020-07-17 18:00:00  11.633872  11.665368  11.615984  11.650719  2088.0
2020-07-17 19:00:00  11.650719  11.667279  11.642955  11.656778  1476.5
2020-07-17 20:00:00  11.656639  11.674149  11.647284  11.670479  2756.5
2020-07-17 21:00:00  11.670339  11.694147  11.667910  11.679684  2044.0
2020-07-17 22:00:00  11.679251  11.694018  11.668609  11.684532  1535.0

In [8]:
1 / pd.Series([0.9568, 110.23, 9.4561, 17.564, 75.544])

0    1.045151
1    0.009072
2    0.105752
3    0.056935
4    0.013237
dtype: float64

In [11]:
1 / pd.DataFrame([(17.456, 17.458), (17.265, 17.298), (17.666, 17.999)], columns=['Open', 'Close'])

       Open     Close
0  0.057287  0.057280
1  0.057921  0.057810
2  0.056606  0.055559

In [14]:
1 / audzar[['open', 'high', 'low', 'close']]

# Inverting OHLC reverses high-low, take care of the volume column. do not inverse it.

                         open      high       low     close
time
2020-07-17 18:00:00  0.085956  0.085724  0.086088  0.085832
2020-07-17 19:00:00  0.085832  0.085710  0.085889  0.085787
2020-07-17 20:00:00  0.085788  0.085659  0.085857  0.085686
2020-07-17 21:00:00  0.085687  0.085513  0.085705  0.085619
2020-07-17 22:00:00  0.085622  0.085514  0.085700  0.085583

# x/y z/x
### USDCHF AUDUSD

In [10]:
1 / usdchf[['open', 'high', 'low', 'close']]

                         open      high       low     close
time
2020-07-17 18:00:00  1.063977  1.063694  1.065190  1.065065
2020-07-17 19:00:00  1.065065  1.064793  1.065587  1.065224
2020-07-17 20:00:00  1.065224  1.065076  1.065689  1.065122
2020-07-17 21:00:00  1.065122  1.064997  1.065814  1.065644
2020-07-17 22:00:00  1.065644  1.065462  1.066075  1.066075

In [11]:
chfusd = 1 / usdchf[['open', 'high', 'low', 'close']]

In [12]:
chfusd / audusd[['open', 'high', 'low', 'close']]

                         open      high       low     close
time
2020-07-17 18:00:00  1.523624  1.520975  1.525426  1.522979
2020-07-17 19:00:00  1.522979  1.521263  1.523813  1.522640
2020-07-17 20:00:00  1.522640  1.521863  1.524351  1.522407
2020-07-17 21:00:00  1.522407  1.520338  1.523636  1.522131
2020-07-17 22:00:00  1.522152  1.521219  1.523226  1.522291

In [5]:
(1/ usdchf[['open', 'high', 'low', 'close']])  * (1/ audusd[['open', 'high', 'low', 'close']])

                         open      high       low     close
time
2020-07-17 18:00:00  1.523624  1.520975  1.525426  1.522979
2020-07-17 19:00:00  1.522979  1.521263  1.523813  1.522640
2020-07-17 20:00:00  1.522640  1.521863  1.524351  1.522407
2020-07-17 21:00:00  1.522407  1.520338  1.523636  1.522131
2020-07-17 22:00:00  1.522152  1.521219  1.523226  1.522291

In [6]:
(usdchf['tick_volume']  + audusd['tick_volume'])/2

time
2020-07-17 18:00:00    2101.5
2020-07-17 19:00:00    1736.0
2020-07-17 20:00:00    1540.5
2020-07-17 21:00:00    1555.0
2020-07-17 22:00:00    1791.0
Name: tick_volume, dtype: float64

# x/y x/z

### USDCHF USDZAR

In [7]:
usdzar[['open', 'high', 'low', 'close']] / usdchf[['open', 'high', 'low', 'close']]

                          open       high        low      close
time
2020-07-17 18:00:00  17.725643  17.742735  17.719323  17.743799
2020-07-17 19:00:00  17.743799  17.748996  17.741680  17.749076
2020-07-17 20:00:00  17.748863  17.766461  17.754550  17.767218
2020-07-17 21:00:00  17.767005  17.779056  17.777650  17.778005
2020-07-17 22:00:00  17.777600  17.789166  17.773928  17.787254

# y/x z/x
### GBPUSD AUDUSD

In [8]:
gbpusd[['open', 'high', 'low', 'close']] / audusd[['open', 'high', 'low', 'close']]

                         open      high       low     close
time
2020-07-17 18:00:00  1.794965  1.794380  1.794627  1.794346
2020-07-17 19:00:00  1.794346  1.795582  1.794391  1.794937
2020-07-17 20:00:00  1.794966  1.795356  1.795454  1.795092
2020-07-17 21:00:00  1.795092  1.794918  1.795317  1.794901
2020-07-17 22:00:00  1.794884  1.795317  1.795093  1.795291

# dollar denominated non-forex / dollar denominated forex
### US500 AUDUSD

In [10]:
(snp500[['open', 'high', 'low', 'close']] / audusd[['open', 'high', 'low', 'close']]).round(2)

                        open     high      low    close
time
2020-07-17 18:00:00  4608.06  4608.85  4603.96  4606.84
2020-07-17 19:00:00  4606.84  4606.68  4603.10  4602.55
2020-07-17 20:00:00  4602.55  4606.13  4601.42  4602.72
2020-07-17 21:00:00  4602.72  4610.99  4603.44  4611.06
2020-07-17 22:00:00  4611.12  4616.93  4606.36  4605.39

# dollar denominated non-forex / non-dollar denominated forex
### US500 USDCHF

In [12]:
(snp500[['open', 'high', 'low', 'close']] * usdchf[['open', 'high', 'low', 'close']]).round(2)

                        open     high      low    close
time
2020-07-17 18:00:00  3024.41  3030.19  3018.15  3024.89
2020-07-17 19:00:00  3024.89  3028.20  3020.78  3022.75
2020-07-17 20:00:00  3022.75  3026.64  3018.61  3023.32
2020-07-17 21:00:00  3023.32  3032.87  3021.35  3029.34
2020-07-17 22:00:00  3029.34  3035.02  3024.08  3025.30

# non-dollar non-forex / dollar-quote forex
### DAX AUDUSD

we need to extract the data from MT5 after determining the nature of asset and currency.

In [22]:
def dollarPair(currency: str):
    if currency in ['EUR', 'GBP', 'AUD', 'NZD']:
        return currency + 'USD'
    else:
        return 'USD' + currency

In [23]:
profitCurrency = mt5.symbol_info('DE30').currency_profit
profitCurrency

'EUR'

In [19]:
def dollarizer(asset, dollarpair):
    
    asset_rates = pd.DataFrame(mt5.copy_rates_from_pos(asset, mt5.TIMEFRAME_H1, 0, 10)).drop(columns=['spread', 'real_volume'])
    dollar_rates = pd.DataFrame(mt5.copy_rates_from_pos(dollarpair, mt5.TIMEFRAME_H1, 0, 10)).drop(columns=['spread', 'real_volume'])
        
    asset_rates['time'] = pd.to_datetime(asset_rates['time'], unit='s')
    dollar_rates['time'] = pd.to_datetime(dollar_rates['time'], unit='s')
        
    asset_rates.set_index(keys=['time'], inplace=True)
    dollar_rates.set_index(keys=['time'], inplace=True)
    
    if dollarpair[3:6] == 'USD':     # quoted in dollar
        dollarised_asset = asset_rates[['open', 'high', 'low', 'close']] * dollar_rates[['open', 'high', 'low', 'close']]
    
    else:                             # based in dollar
        dollarised_asset = asset_rates[['open', 'high', 'low', 'close']] / dollar_rates[['open', 'high', 'low', 'close']]
        dollarised_asset.rename(columns={'high': 'low', 'low': 'high'})
    
    dollarised_asset['vol'] = (asset_rates['tick_volume'] + dollar_rates['tick_volume']) / 2
    return dollarised_asset

In [21]:
dollarizer("DE30", 'EURUSD').round(2)

                         open      high       low     close     vol
time
2020-07-17 13:00:00       NaN       NaN       NaN       NaN     NaN
2020-07-17 14:00:00  14763.34  14769.53  14716.24  14752.71  3134.5
2020-07-17 15:00:00  14752.66  14790.99  14732.16  14741.93  3155.5
2020-07-17 16:00:00  14741.93  14791.28  14722.90  14771.32  5991.0
2020-07-17 17:00:00  14762.28  14795.01  14719.94  14769.27  6205.0
2020-07-17 18:00:00  14768.36  14810.24  14755.42  14803.48  4802.5
2020-07-17 19:00:00  14803.48  14822.40  14782.29  14790.55  2756.5
2020-07-17 20:00:00  14790.55  14805.16  14777.40  14792.12  2285.0
2020-07-17 21:00:00  14792.12  14820.16  14788.70  14801.06  1981.5
2020-07-17 22:00:00  14800.10  14845.52  14788.86  14830.79  2615.5
2020-07-17 23:00:00       NaN       NaN       NaN       NaN     NaN

# non-dollar non-forex / dollar based forex.
### NOR25 USDNOK

In [35]:
dollarizer('NOR25', dollarPair(mt5.symbol_info('NOR25').currency_profit))

                          open       high        low      close     vol
time
2020-07-16 16:00:00        NaN        NaN        NaN        NaN     NaN
2020-07-16 17:00:00        NaN        NaN        NaN        NaN     NaN
2020-07-17 10:00:00        NaN        NaN        NaN        NaN     NaN
2020-07-17 11:00:00        NaN        NaN        NaN        NaN     NaN
2020-07-17 12:00:00        NaN        NaN        NaN        NaN     NaN
2020-07-17 13:00:00        NaN        NaN        NaN        NaN     NaN
2020-07-17 14:00:00  81.015113  80.974035  80.998390  81.003565  2203.5
2020-07-17 15:00:00  81.008950  81.063134  81.080207  81.054868  2003.0
2020-07-17 16:00:00  81.049486  81.209811  81.162113  81.235354  3969.5
2020-07-17 17:00:00  81.240741  81.131881  81.177674  81.013724  3872.5
2020-07-17 18:00:00        NaN        NaN        NaN        NaN     NaN
2020-07-17 19:00:00        NaN        NaN        NaN        NaN     NaN
2020-07-17 20:00:00        NaN        NaN        NaN        NaN     NaN
2020-07-17 21:00:00        NaN        NaN        NaN        NaN     NaN
2020-07-17 22:00:00        NaN        NaN        NaN        NaN     NaN
2020-07-17 23:00:00        NaN        NaN        NaN        NaN     NaN

In [44]:
asset_rates = pd.DataFrame(mt5.copy_rates_from_pos('NOR25', mt5.TIMEFRAME_H1, 0, 100)).drop(columns=['spread', 'real_volume'])
dollar_rates = pd.DataFrame(mt5.copy_rates_from_pos('USDNOK', mt5.TIMEFRAME_H1, 0, 100)).drop(columns=['spread', 'real_volume'])
asset_rates['time'] = pd.to_datetime(asset_rates['time'], unit='s')
dollar_rates['time'] = pd.to_datetime(dollar_rates['time'], unit='s')
        
asset_rates.set_index(keys=['time'], inplace=True)
dollar_rates.set_index(keys=['time'], inplace=True)

In [45]:
asset_rates

                       open    high     low   close  tick_volume
time
2020-07-01 17:00:00  720.46  722.79  719.38  722.07          329
2020-07-02 10:00:00  717.89  723.09  716.99  720.74          934
2020-07-02 11:00:00  720.69  721.47  718.95  720.73          416
2020-07-02 12:00:00  720.68  720.89  719.48  720.41          124
2020-07-02 13:00:00  720.36  721.66  720.36  721.40          238
...                     ...     ...     ...     ...          ...
2020-07-17 13:00:00  750.74  752.17  750.20  751.14          259
2020-07-17 14:00:00  751.13  752.15  750.80  752.11          243
2020-07-17 15:00:00  752.16  753.19  751.80  752.99          375
2020-07-17 16:00:00  752.94  754.47  752.29  753.99          370
2020-07-17 17:00:00  754.04  754.09  752.28  752.53          185

[100 rows x 5 columns]

In [46]:
dollar_rates

                        open     high      low    close  tick_volume
time
2020-07-13 20:00:00  9.37042  9.37152  9.35998  9.36668         2131
2020-07-13 21:00:00  9.36668  9.41372  9.36668  9.40552         4722
2020-07-13 22:00:00  9.40552  9.45632  9.40542  9.43782         6348
2020-07-13 23:00:00  9.43772  9.46468  9.43772  9.45349         5732
2020-07-14 00:00:00  9.45256  9.45256  9.43445  9.44169         1983
...                      ...      ...      ...      ...          ...
2020-07-17 19:00:00  9.27005  9.28082  9.26712  9.27932         3220
2020-07-17 20:00:00  9.27962  9.28362  9.27312  9.28262         2950
2020-07-17 21:00:00  9.28262  9.28702  9.27322  9.27612         1946
2020-07-17 22:00:00  9.27612  9.28568  9.27182  9.27772         2200
2020-07-17 23:00:00  9.27716  9.28828  9.27142  9.28668         4121

[100 rows x 5 columns]

In [50]:
dollarised_asset = asset_rates[['open', 'high', 'low', 'close']] / dollar_rates[['open', 'high', 'low', 'close']]
# dollarised_asset.rename(columns={'high': 'low', 'low': 'high'}, inplace=True)
dollarised_asset.dropna(inplace=True)
dollarised_asset

                          open       high        low      close
time
2020-07-14 10:00:00  77.474853  77.652713  77.488129  77.517547
2020-07-14 11:00:00  77.524667  77.760022  77.676489  77.870751
2020-07-14 12:00:00  77.876039  78.190610  77.967302  78.349093
2020-07-14 13:00:00  78.353331  78.288639  78.210595  78.362754
2020-07-14 14:00:00  78.361923  78.300452  78.268898  78.411544
2020-07-14 15:00:00  78.411544  78.364674  78.422596  78.280430
2020-07-14 16:00:00  78.286790  78.199583  78.291910  78.495975
2020-07-14 17:00:00  78.502949  78.370022  78.594580  78.606756
2020-07-15 05:00:00  79.037352  78.908184  79.048685  78.926479
2020-07-15 10:00:00  79.688463  80.109459  80.136255  80.414986
2020-07-15 11:00:00  80.409622  80.275716  80.195934  80.090564
2020-07-15 12:00:00  80.085201  80.130442  80.028143  80.143579
2020-07-15 13:00:00  80.148935  80.404502  80.321095  80.454674
2020-07-15 14:00:00  80.460042  80.574078  80.645578  80.803451
2020-07-15 15:00:00  80.798680  81.031137  80.837685  81.025246
2020-07-15 16:00:00  81.026323  80.811116  80.970643  80.701860
2020-07-15 17:00:00  80.712594  80.666237  80.873908  80.939760
2020-07-16 07:00:00  80.825304  80.799277  80.851347  80.837455
2020-07-16 08:00:00  80.837455  80.736015  80.852216  80.823915
2020-07-16 10:00:00  80.169776  80.433586  80.318925  80.432346
2020-07-16 11:00:00  80.384026  80.232163  80.173029  80.103262
2020-07-16 12:00:00  80.107380  80.187478  80.056643  80.024094
2020-07-16 13:00:00  80.022296  80.106999  80.182143  80.171530
2020-07-16 14:00:00  80.171530  80.165729  80.367300  80.361193
2020-07-16 15:00:00  80.360118  80.400866  80.495643  80.400919
2020-07-16 16:00:00  80.393817  80.385190  80.629131  80.568465
2020-07-16 17:00:00  80.563076  80.524685  80.671559  80.736446
2020-07-17 10:00:00  80.672719  80.846553  80.583625  80.591368
2020-07-17 11:00:00  80.596742  80.780743  80.776558  80.989433
2020-07-17 12:00:00  80.984045  80.907907  80.817239  80.777169
2020-07-17 13:00:00  80.783625  80.921827  80.923534  81.016192
2020-07-17 14:00:00  81.015113  80.974035  80.998390  81.003565
2020-07-17 15:00:00  81.008950  81.063134  81.080207  81.054868
2020-07-17 16:00:00  81.049486  81.209811  81.162113  81.235354
2020-07-17 17:00:00  81.240741  81.131881  81.177674  81.013724

In [42]:
dollarised_asset.plot()